### PR TITLE
feat: update SDK to support Appwrite 0.12.x and above

### PR DESCRIPTION
**Pull request by brandonroberts**
BREAKING CHANGES:

The minimum version of Appwrite has been updated

BEFORE:

SDK supports Appwrite 0.11.x and below

AFTER:

SDK supports Appwrite 0.12.x and above

### CODE REVIEW

**Comment by MarvinJWendt** [comment]
Just a quick reminder to update the README, as new parameters, like userId were introduced 😄

**Comment by brandonroberts** [comment]
@MarvinJWendt good catch! I'll update those also

**Comment by koodeau** [comment]
there are definitely going to be some breaking changes, you can compare to [my a bit reworked version](https://github.com/koodeau/metawrite) of this outdated package

**Comment by stnguyen90** [comment]
Closing stale PR

**Pull request closed without merging**
